DROP TABLE HIT_AFFECTED CASCADE CONSTRAINTS;

CREATE TABLE HIT_AFFECTED
(
 SUB_ID NUMBER(10) NOT NULL PRIMARY KEY,
 CODIGOCIRCUITO VARCHAR2(6) NOT NULL REFERENCES CIRCUITO
);

GRANT SELECT, INSERT, DELETE, UPDATE ON HIT_AFFECTED TO ADMINISTRADORENERGIS; 

DROP TABLE HIT_NODE CASCADE CONSTRAINTS;

CREATE TABLE HIT_NODE
(
NID     VARCHAR2(40) PRIMARY KEY NOT NULL,
NNAME       VARCHAR2(40),
SUB_ID     NUMBER(10),
ABB_INT_ID     NUMBER(10),
TIPO VARCHAR2(40),
TENSION FLOAT, 
XN_1      FLOAT(126),
YN_1     FLOAT(126),
LON      FLOAT(126),
LAT     FLOAT(126)
);

GRANT SELECT, INSERT, DELETE, UPDATE ON HIT_NODE TO ADMINISTRADORENERGIS;


DROP TABLE HIT_LINE CASCADE CONSTRAINTS;
CREATE TABLE HIT_LINE
(
ID     VARCHAR2(40) PRIMARY KEY NOT NULL,
NAME       VARCHAR2(40),
ABB_INT_ID     NUMBER(10),
NO_KEY_1      NUMBER(10),
NO_KEY_2      NUMBER(10),
LENGTH      NUMBER(10,3),
TIPO_CONDUCTOR VARCHAR2(40),
CAPACIDAD_AMP      NUMBER(10),
CODIGOAPOYO1 FLOAT,
CODIGOAPOYO2 FLOAT
);

GRANT SELECT, INSERT, DELETE, UPDATE ON HIT_LINE TO ADMINISTRADORENERGIS; 


DROP TABLE HIT_LONGITUDES CASCADE CONSTRAINTS;
CREATE TABLE HIT_LONGITUDES
(
ABB_INT_ID     NUMBER(10)  PRIMARY KEY NOT NULL,
LENGTH      NUMBER(10,3)
);

--CREATE INDEX HIT_LINE_NID_NO_KEY_1 ON HIT_LINE (NID_NO_KEY_1);

--CREATE INDEX HIT_LINE_NID_NO_KEY_2 ON HIT_LINE (NID_NO_KEY_2);

GRANT SELECT, INSERT, DELETE, UPDATE ON HIT_LONGITUDES TO ADMINISTRADORENERGIS; 
